{!! Theme::partial('home-page-new/header') !!}
{!! Theme::partial('home-page-new/why-choose') !!}
{!! Theme::partial('home-page-new/how-it-works') !!}
{!! Theme::partial('home-page-new/about-us') !!}
{!! Theme::partial('home-page-new/property-categories') !!}
{!! Theme::partial('home-page-new/meet-agents') !!}
{!! Theme::partial('home-page-new/testimonials') !!}
{!! Theme::partial('home-page-new/cta-move') !!}
{!! Theme::partial('home-page-new/site-footer') !!}
{!! Theme::partial('home-page-new/footer') !!}